# Generated by Django 5.0.1 on 2024-02-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_category', models.CharField(max_length=128)),
                ('category_date_category', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_event', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_to_category',
            field=models.ManyToManyField(blank=True, related_name='category_event', to='events.category'),
        ),
    ]
