# Generated by Django 5.0.1 on 2024-02-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_alter_comment_comment_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
