# Generated by Django 5.0.1 on 2024-02-20 14:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
                ('category_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=256, verbose_name='Название статьи')),
                ('content', ckeditor.fields.RichTextField(verbose_name='')),
                ('article_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации статьи')),
                ('cover_image', models.ImageField(default='defaults/wrc_emblem.webp', upload_to='articles/')),
                ('article_to_category', models.ManyToManyField(blank=True, related_name='category_article', to='articles.category')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author_article', models.CharField(max_length=256, verbose_name='Автор комментария статьи')),
                ('comment_text_article', models.TextField(verbose_name='Текст комментария статьи')),
                ('comment_date_article', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария статьи')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
