# Generated by Django 5.0.1 on 2024-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_alter_article_article_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_to_category',
            field=models.ManyToManyField(blank=True, to='articles.category'),
        ),
    ]
