# Generated by Django 5.0.1 on 2024-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_article_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author_article',
            field=models.CharField(max_length=256, verbose_name='Автор комментария статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text_article',
            field=models.TextField(verbose_name='Текст комментария статьи'),
        ),
    ]
