# Generated by Django 5.0.1 on 2024-02-12 12:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name=' '),
            preserve_default=False,
        ),
    ]
