# Generated by Django 5.0.1 on 2024-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_article_text_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='defaults/wrc_emblem.webp', upload_to='articles/'),
        ),
    ]
