# Generated by Django 5.0.1 on 2024-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='articles/wear_warm.webp', upload_to='articles/'),
        ),
    ]
