# Generated by Django 5.0.1 on 2024-02-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=256, verbose_name='Название новости')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('news_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author_news', models.CharField(max_length=256, verbose_name='Автор комментария новости')),
                ('comment_text_news', models.TextField(verbose_name='Текст комментария новости')),
                ('comment_date_news', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария новости')),
                ('comment_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
