# Generated by Django 5.0.1 on 2024-02-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_news', models.CharField(max_length=128)),
                ('category_date_news', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_news', to='news.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_to_category',
            field=models.ManyToManyField(blank=True, related_name='category_news', to='news.category'),
        ),
    ]
