# Generated by Django 5.0.1 on 2024-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(default='defaults/wrc_emblem.webp', upload_to='news/'),
        ),
    ]
