# Generated by Django 5.0.1 on 2024-02-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rapcreated_date',
            new_name='created_date',
        ),
    ]
